### ISSUE TITLE
Corner Case when setting num.trees 

### ISSUE THREAD

**Issue by rajisme** [swager/grf#102]
There's a corner case where R crashes when num.trees is less than 8 on my computer:

library(grf)

# Generate data.
n = 2000; p = 10
X = matrix(rnorm(n*p), n, p)
X.test = matrix(0, 101, p)
X.test[,1] = seq(-2, 2, length.out = 101)

# Perform treatment effect estimation.
W = rbinom(n, 1, 0.5)
Y = pmax(X[,1], 0) * W + X[,2] + pmin(X[,3], 0) + rnorm(n)
tau.forest = causal_forest(X, Y, W, num.trees=7)

R then aborts on my computer instantly.

**Comment by jtibshirani** [comment]
Thank you for the bug report! We'll try to get this resolved as soon as possible.

**Comment by rajisme** [comment]
No problem! I really appreciate you all open sourcing the code!
