### ISSUE TITLE
Remove embedded copy of Eigen3 and use 'LinkingTo: RcppEigen'

### ISSUE THREAD

**Issue by eddelbuettel** [swager/grf#146]
The underlying CRAN package could be made lighterweight by re-using the Eigen headers as shipped by RcppEigen.  Many other packages do (currently 127 reverse depends).  Code duplication is generally seen as something to avoid.  Obviously, as for other rules there we may be good exceptions and I may be overlooking something here.

But I tested this real quick by starting from yesterday's CRAN upload; just making in 'LinkingTo: Rcpp, RcppEigen' was all it took; I could then remove the `src/third_party` subtree.   Happy to send a PR if you're interested.

**Comment by eddelbuettel** [comment]
FWIW:  

```diff
/tmp/grf$ diff -ru grf.orig/ grf
diff -ru grf.orig/DESCRIPTION grf/DESCRIPTION
--- grf.orig/DESCRIPTION        2017-11-27 02:49:29.000000000 -0600
+++ grf/DESCRIPTION     2017-11-27 16:03:53.387221249 -0600
@@ -1,6 +1,6 @@
 Package: grf
 Title: Generalized Random Forests (Beta)
-Version: 0.9.4
+Version: 0.9.4.1
 Author: Julie Tibshirani [aut, cre],
     Susan Athey [aut],
     Stefan Wager [aut],
@@ -15,7 +15,7 @@
     improvements to its performance and usability.
 Depends: R (>= 3.3.1)
 License: GPL-3
-LinkingTo: Rcpp
+LinkingTo: Rcpp, RcppEigen
 Imports: Rcpp (>= 0.12.10)
 RoxygenNote: 6.0.1
 Suggests: sandwich, testthat
Only in grf: grf_0.9.4.1.tar.gz
diff -ru grf.orig/src/Makevars grf/src/Makevars
--- grf.orig/src/Makevars       2017-11-26 17:30:45.000000000 -0600
+++ grf/src/Makevars    2017-11-28 09:31:09.200124034 -0600
@@ -4,7 +4,7 @@
 CC=/usr/local/bin/gcc-4.9
 CXX=/usr/local/bin/g++-4.9

-PKG_CXXFLAGS = -I. -Isrc -Ithird_party -DR_BUILD
+PKG_CXXFLAGS = -I. -Isrc -DR_BUILD

 SOURCES = $(wildcard *.cpp */*.cpp */*/*.cpp */*/*/*.cpp)
 OBJECTS = $(SOURCES:.cpp=.o)
Only in grf.orig/src: third_party
/tmp/grf$
```

**Comment by eddelbuettel** [comment]
Also, I noticed the settings for `CC` and `CXX` in `src/Makevars`:  I was fighting the same issue at work last week(s) with code (by others) needing that compiler.  One cannot set it there as Duncan Murdoch calmly reminded me on r-package-devel, see https://stat.ethz.ch/pipermail/r-package-devel/2017q4/002087.html fpr his post (and mine preceeding/following).

**Comment by jtibshirani** [comment]
Thank you @eddelbuettel for the suggestions and diff! As we discussed over email, we can't get rid of the Eigen source altogether, as we'd like to preserve the ability to run as a standalone C++ package. For now we've gone with a hybrid approach, where the Eigen source is used for C++ development, but is excluded in favor of RcppEigen when building the R package.
