### ISSUE TITLE
Panel data implementation

### ISSUE THREAD

**Issue by andreacaflisch** [swager/grf#147]
I am very interested in using your algorithm to estimate heterogeneous treatment effects, but cannot find any documentation on whether and how it can be applied to panel data. Is there a way of implementing your model that is compatible with the standard fixed effects unbiasedness assumptions?

**Comment by swager** [comment]
Hi @andreacaflisch, we are very interested in exploring the use of GRF with panel data, but don't have a public implementation ready yet. Once we have one, it will be added to this package.

**Comment by NicolasWoloszko** [comment]
Dear @swager 
How wrong would it be to use a fixed effects model by unit-demeaning beforehand or including unit fixed effects in the orthogonalisation step ? 
I plan to use this approach to apply GRF to household micro-data spanning multiple countries and years, and thus including country fixed effects or country demeaning in the model. 
Thanks a lot !

**Comment by swager** [comment]
De-meaning units before the analysis seems like a reasonable thing to do. Other options that may be helpful are:
- Encoding fixed effects as described here: https://arxiv.org/pdf/1908.09874.pdf
- Using the cluster option in `causal_forest` to cluster by unit
