### ISSUE TITLE
Feature importance

### ISSUE THREAD

**Issue by adamonkey** [swager/grf#219]
If I understand the package correctly, all the methods produce a forest in the end. I am interested in understanding which variables drive the most heterogeneity in treatment effects. So that I can then show 1 group 1 message, and another group another message - it would be easier to implement from an infrastructure standpoint than predicting a treatment effect for each individual. 

I am interested in adding the ability to output feature importances, would this be difficult? Or alternatively, is there a way to create 1 well-grown tree? Thank you in advance!

**Comment by axustash** [comment]
Sorry! I see that this is already possible. Thanks for the great package.

**Comment by adamonkey** [comment]
Sorry! I see that this is already possible, through variable importance. If that is not it, I can always use the splits. Thanks for the great package.
