### ISSUE TITLE
What does it mean that one of the samples in a final node of a tree is zero?

### ISSUE THREAD

**Issue by rduncant** [swager/grf#246]
Hello,

I trying to understand the  output information of one tree from a causal forest.
In this example, the number of training samples is 772.

> tau.forest = causal_forest(x, y, z, num.trees = 500)
> tree1=get_tree(tau.forest, 1)
I print out one of the final node of this tree and I get this output
>tree1$nodes[5]
[[1]]
[[1]]$is_leaf
[1] TRUE
[[1]]$samples
 [1] 113 694 712 705 232 584 704  0 718  19 700 109

What does it mean that one of the samples of this final node is zero? 
Is it possible to have access to the source code of  '_grf_instrumental_train'?
Thanks.

**Comment by predt** [comment]
I just realized that  you must add 1 to each sample index contained in the "drawn_samples" and final nodes outputs of a tree to get the correct row index in the data. Therefore, a sample index in a final node equal to zero means "sample point of row 1" in the data frame [x,y,z].

**Comment by jtibshirani** [comment]
Hi @rduncant thank you for the ticket, and apologies for the slow response! @predt is right in that these indices come straight from C++ and are 0-indexed, as opposed to 1-indexed.

This is a bug, as 1-indexing is the standard in R, and we'll plan to fix it in a future release.

**Comment by jtibshirani** [comment]
This issue was fixed in #266.
