### ISSUE TITLE
About predicted values

### ISSUE THREAD

**Issue by predt** [swager/grf#248]
Hello,
About the OptimizedPredictionStrategy.  The code says "only 'optimized' prediction strategies can provide variance estimates" and "OptimizedPredictionStrategy does not predict using a list of neighboring samples and weights".

Following your example:
>#Predict with confidence intervals; growing more trees is now recommended.
>c.forest = causal_forest(X, Y, W, num.trees = 4000)
 >c.pred = predict(c.forest, X.test, estimate.variance = TRUE)

Does this mean that cpred$predictions were not calculated using the weights (i.e. equation 19 in "Generalized Random Forest" paper was not used)?
Many thanks.

**Comment by swager** [comment]
@predt, the "optimized" and "regular" prediction strategies are statistically identical (i.e., they both compute the same thing); we just compute things in a different order to speed up the implementation.

The main point is that explicitly computing the neighborhood weights is quite expensive. So what the "optimized" strategy does is to cache some sufficient statistics averaged over tree leaves (e.g., the average of W, W^2, WY, etc.), and then uses those to compute treatment effect estimates. But the resulting estimates are exactly the same as you'd get with the explicit neighborhood weighting.

**Comment by predt** [comment]
@swager, many thanks for the explanation.
