### ISSUE TITLE
Updating Predicted Values While Maintaining Current Tree (Forest) Structure with Regression_Forest

### ISSUE THREAD

**Issue by JREED1234** [swager/grf#250]
Hello,

Thank you, once again, for answering my question a few months back. It has been immensely helpful. Though, I do have a new question for you. I am trying to see if there is a way to open up the tree/forest structure to update the predicted (Y) values while maintaining the tree/forest structure for a given regression_forest object. 

For example, assume that you use a set of X variables and a response of Y, which gives you forest object F. This forest object has the samples at each terminal node (shown from the forest$node). Is there a way to insert a new set of Y's, say Y', keeping the same object F? This is for an iterative project where I want to maintain the flexible, predictive nature of the forest object, but I need to update Y's recursively. I am finding that, with re-estimation of new forest objects at each iteration causes very minute instability that I believe can be resolved if a forest object can be maintained where the predicted values from the leaves can be updated. 

I hope this is clear enough.

**Comment by jtibshirani** [comment]
Hi @JREED1234, thank you for the ticket! Unfortunately what you've described isn't currently supported. The forest is grown in C++, and is stored in a compressed, opaque representation the C++ core code understands (`forest$serialized.forest`). The different components you can inspect in R are just user-friendly copies of the actual representation, and changing them wouldn't change the forest's behavior going forward (for example, what predictions it makes).

Would it be possible to describe your use case in a bit more detail? With more information about what you're trying to accomplish, we may be able to help brainstorm a workaround using what the package can currently do.

**Comment by JREED1234** [comment]
Thank you so much for your quick response to my rather odd query. I had
figured the object was in C++, but I thought I would ask anyway.

So, I have been thinking this over myself and looking at the documentation
on the data.tree structure (which I believe is close to what I view with
the get_tree function). Is there anyway, given the way your code is
structured, to return what leaf, for a given tree, a vector of x's would
reside in? For example, if I estimate a regression forest and then extract
a single tree and use something akin to the predict function with a single
tree an a matrix of X variables, I can get a vector out of which leaf each
row of the matrix would reside in within the tree? I have in my head a work
around for the iterative procedure I need to accomplish, and I believe if I
can get a vector of leaves that correspond to a matrix of inputs, it should
work. Basically, instead of returning the actual predicted values, the
vector would return the leaf number for a given tree (or even better, a
matrix with the leaf number across all trees in the regression forest).

Let me know if you need any further details. Thanks again for your help!

James

**Comment by susanathey** [comment]
This would also be useful for other purposes, like estimating a parameter within each leaf and calculating the standard deviation; or for visualizing how the weights are formed.

**Comment by jtibshirani** [comment]
There's not currently a way to return the leaf a test sample would belong to. This indeed seems like a nice feature to have -- I've labelled the ticket to make sure we track the improvement. It's unfortunately unlikely that we'll get to this soon because of limited bandwidth, but will keep you updated.

**Comment by JREED1234** [comment]
Thanks for the update! I know you all are very busy. I will try to come up
with a work-a-round on my end.

James

**Comment by jtibshirani** [comment]
After re-reading the thread, I noticed that you're using a plain `regression_forest`, and another option came to mind. We recently added a method `get_sample_weights` that allows you to retrieve the weights of training samples given a set of test points: https://github.com/swager/grf/blob/master/r-package/grf/R/analysis_tools.R#L122. These weights represent how often a training sample has been in the same leaf as the test sample (normalized by the size of the leaf).

For regression forests, a prediction is simply the sum over all training samples of a sample's weight times its outcome (`y` value). So to recalculate the predictions with different outcomes, you could compute the original sample weight matrix using `get_sample_weights`, and multiply it with the new outcome vector.

The formulation involving sample weights is different from how regression forest prediction is usually described, but it should be mathematically equivalent, and is the approach taken in this package.

**Comment by JREED1234** [comment]
Julie:

That is a perfect solution for my problem. Thank you so much for taking the
time to think about this problem and provide me with a quick and useful
solution.

James
