### ISSUE TITLE
Assumptions required for continuous treatment

### ISSUE THREAD

**Issue by tabacof** [swager/grf#256]
If I understood correctly, for binary treatments we have the following main assumptions (besides Lipschitz continuity):

1. Unconfoundedness: (Y1, Y0) ⊥ W|X (i.e. given the features, the response is independent of the treatment)
2. Overlap: ε < p(W=1|X) < 1-ε (i.e given the features the treatment is not deterministic)

What would the equivalent be for the continuous treatment case (where W is real)?

**Comment by swager** [comment]
The assumptions in the binary case are particularly simple and nice. In contrast, in the continuous case, we need somewhat stronger modeling assumptions.

At a high level, whenever you can write a model

Y = m(X) + W tau(X) + epsilon,   E[epsilon | W, X] = 0,

then `causal_forest` will consistently estimate tau(x). Note that, in the binary case, we get this representation directly (with m(x) = E[Y | X = x, W=0], tau(x) = E[Y | X = x, W=1] - m(x), and epsilon = Y - E[Y | X, W], and thanks to unconfoundedness all moments have the desired causal interpretations).

More generally, even when the above model doesn't hold, `causal_forest` always consistently estimates

"tau(x)" = Cov[Y, W | X = x] / Var[W | X = x].

Without further assumptions, though, this parameter does not have a causal interpretation.

**Comment by ginward** [comment]
Excellent question!
