### ISSUE TITLE
Individual tree visualization using Graphviz

### ISSUE THREAD

**Issue by Buyannemekh** [swager/grf#286]
Here is a proposed idea for individual tree visualization (raised in issue #277, #105 ). 
Instead of using `rpart.plot`, we can use [Graphviz](https://www.graphviz.org/) open source data visualization software, which takes `dot` file that has information of a graph in text language to visualize the graph. 

Currently, we have written a function `create_dot_string()` ([link](https://gist.github.com/Buyannemekh/f6d8c306af3aec2ef1e252fe1770977f)) that generates `dot` text simply from individual tree nodes information in `R`. 
```
c_tree <- get_tree(c_forest, 1)
create_dot(c_tree$nodes)
```
As shown in the example above, the function `create_dot_string` output this text:

```
digraph nodes { 
  size= '6,6'; 
  node [shape=box] ;
  0 [label="split_variable 8 <= -0.65 "] ;
  0 -> 1 [labeldistance=2.5, labelangle=45, headlabel="True"];
  0 -> 2 [labeldistance=2.5, labelangle=-45, headlabel="False"]
  1 [label="split_variable 8 <= -0.99 "] ;
  1 -> 3  ;
     .... abbreviated .....
  14 -> 19  ;
  14 -> 20  ;
  19 [label="leaf 20 "];
  20 [label="leaf 21 "];
}
```

The figure below shows a tree plot that was generated using the output above, via graphviz's command line. We can also write a simple wrapper in R for the command line interface.

<img width="876" alt="screen shot 2018-08-14 at 7 47 16 pm" src="https://user-images.githubusercontent.com/10742320/44129193-05fdf9a4-9ffc-11e8-977c-e3abfbad7acd.png">

Right now, it's showing a ` splitting variable` ( 8 is the 8th column of the data frame in this case) with the corresponding `splitting value`. This is currently just as a placeholder and we can change it to something else as well. Graphviz also supports other shapes, color schemes, arrow formats, etc.

Ultimately, for compatibility with different languages, it'd be better to move this `dot` generating function to the C++ code, but for now this should serve as good prototype.

We are proposing this because it was more versatile (we can use it in Python, C++, and R) instead of using `rpart.plot` or writing a function that convert `grf_tree` to `rpart` object. However, it will be dependent on this different software, which is open-source.

Please let me know what are your thoughts on this.

**Comment by jtibshirani** [comment]
I really like the idea of using Graphviz! The prototype you wrote looks very promising, and it's great that the format is language-agnostic.

One aspect that would be good to discuss: I think part of the reason we considered `rpart` was that it would allow us to prune trees before plotting them. My understanding is that trees can be very difficult to interpret without some preprocessing (removing branches with very few examples, etc.). I wonder how pruning would fit into this approach, and generally how much functionality we anticipate needing around preprocessing trees.

**Comment by Buyannemekh** [comment]
Thanks for the feedbacks! 

@swager I feel like [DiagrammeR](https://github.com/rich-iannone/DiagrammeR) is great for creating network graph diagrams, but not for trees? Also, I am not sure DiagrammeR's flexibility on changing the node color, size and displaying more information on each node. 

@jtibshirani In my experience of using [export_graphviz()](https://github.com/scikit-learn/scikit-learn/blob/f0ab589f/sklearn/tree/export.py#L74) to generate a decision tree in `scikit-learn` was I simply pass the optimal decision tree and get the corresponding `dot` file. However, it looks like they have this optional parameter `max_depth` that takes the maximum depth of the representation if any integer given, if none, the tree is fully generated. If this is not a good approach, we could definitely dig into more about how to prune trees effectively before printing them out.

**Comment by susanathey** [comment]
When I have manipulated trees in rpart I have first pruned and then plotted.  I think those operations could be separated.  The shortcut of making an rpart tree is that there were existing routines to do both operations.  But we are building our own now, I think we do need a prune function that lets us take snippets of trees and ideally it would be flexible, the print command can take in a tree (that might have been snipped in any variety of ways) and then plot it.

**Comment by swager** [comment]
Agreed -- pruning trees is a core statistical task that shouldn't be tied to plotting. So we should have an API that lets you get a tree, then prune the tree if you want, and finally plot the tree.

@Buyannemekh the main reason I was looking at DiagrammeR is that it would let us import graphviz in a very simple way (because DiagrammeR is on CRAN, we can just list it as a dependency and we're done). If we try to depend on a non-CRAN resources for the R package, then there's much more overhead. (Also, I thought DiagrammeR essentially included an interface to graphviz, so would be surprised if there were major limitation like that?)

That being said, if you have another CRAN-based solution for using graphviz, I'd also be happy to go with that!

**Comment by Buyannemekh** [comment]
@swager I investigated DiagrammeR more and found that we can use `grViz()` in which we can pass the `dot` file to plot the trees. 

<img width="1440" alt="screen shot 2018-08-16 at 3 48 40 pm" src="https://user-images.githubusercontent.com/10742320/44239165-de205180-a16c-11e8-9d0c-cbf669677ec3.png">

Also, it is very powerful that we can generate more interactive plots using this. Currently, we can plot any given tree with an implementation of dot file and DiagrammeR. I agree that it'd be very useful to have a prune function on trees before plotting it.

**Comment by susanathey** [comment]
This looks great!  Can we see an example where the leaves show a few different statistics (e.g. CATE, standard error, number of observations) and the splitting boxes look different from the leaf boxes?

**Comment by Buyannemekh** [comment]
![colored-leaf](https://user-images.githubusercontent.com/10742320/44242794-7c69e280-a180-11e8-82b5-70230991b209.png)

**Comment by jtibshirani** [comment]
Thanks for the thoughts on pruning. It sounds like we should keep this issue scoped to just tree visualization, and when we're ready to add pruning, we can follow up with another issue.

I like the idea of eventually allowing the GraphViz output to be returned from the C++ API, but I agree that in this first version, we should do what's easiest to implement and can do the translation in R.

**Comment by Buyannemekh** [comment]
With @jtibshirani 's help and suggestion, I have tried to create a R object that represent a graph using DiagrammeR's `create_graph()` function instead of directly writing `dotfile` from the node's information using  `get_tree()`. Although this approach could have been less error prone, there were some complications around customizing the shape and style of the nodes. Therefore, we are planning to go with building dot string from tree information directly and plot it using `grViz()` in DiagrammeR. Following image shows an example output of `plot()`. 
<img width="1440" alt="screen shot 2018-09-14 at 2 48 28 pm" src="https://user-images.githubusercontent.com/10742320/45577026-e680b080-b82e-11e8-843c-28b458542ef3.png">

**Comment by jtibshirani** [comment]
@Buyannemekh merged added basic support for plotting trees in #296. I opened #298 to track additional improvements.
